dist: xenial
sudo: false
language: ruby
rvm:
- 2.7
- 3.0
env:
  global:
  - TRAVIS=1 CI=1 COVERAGE=1
cache: bundler
bundler_args: --without debug

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- bundle exec rspec --format d
- bundle exec rubocop
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
